[tool.poetry]
name = "erikbarkov"
version = "0.1.0"
description = ""
authors = ["trojvn <mrx.trojan@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
python-dotenv = "^1.0.1"
seleniumbase = "^4.37.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
